export const Routes = {
  Home: 'Home',
  HomeScreen: 'HomeScreen',
  DonationPage: 'DonationPage',
  Profile: 'Profile',
  Chats: 'Chats',
  ChatDetail: 'ChatDetail',
  Search: 'Search',
  Settings: 'Settings',
  SelectionScreen: 'SelectionScreen',
  Explore: 'Explore',
  Spotlight: 'Spotlight',
  Notification: 'Notification',
  Event: 'Event',
  News: 'News',
  Create: 'Create',
  Post: 'Post',
  EventDescription: 'EventDescription',
  Welcome: 'Welcome',
  LogIn: 'LogIn',
  SignUp: 'SignUp',
  UserTypeSelection: 'UserTypeSelection',
  CharitySignUp: 'CharitySignUp',
  DonorSignUp: 'CharitySignUp',
};
